config/routes.rb
Rails.application.routes.draw do

  get 'articles/interesting_insights'
  get 'articles/national_household_survey'
  get 'articles/census_bc'
  get 'articles/municipal'
  get 'articles/development_region'
  get 'articles/provincial'  
  get 'articles/index'
  
  root 'articles#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = [
      {
        "author": "John Doe",
        "date": "2017-02-15",
        "id": "provincial",
        "title": "Provincial Monthly for Property Transfer Tax",
        "description": "Please add a description here",
        "tags": ["provincial","property","transfer","tax"],
        "path": articles_provincial_path
      },
      {
        "author": "John Doe",
        "date": "2017-02-15",
        "id": "development_region",
        "title": "Development Region Monthly for Property Transfer Tax",
        "description": "Please add a description here",
        "tags": ["development","region","property","transfer","tax"],
        "path": articles_development_region_path
      },
      {
        "author": "John Doe",
        "date": "2017-02-15",
        "id": "municipal",
        "title": "Municipal Monthly for Property Transfer Tax",
        "description": "Please add a description here",
        "tags": ["municipal","property","transfer","tax"],
        "path": articles_municipal_path
      },
      {
        "author": "John Doe",
        "date": "2017-02-15",
        "id": "census2016",
        "title": "Census of B.C. 2016",
        "description": "Please add a description here",
        "tags": ["census","bc","2016","population"],
        "path": articles_census_bc_path
      },
      {
        "author": "John Doe",
        "date": "2017-02-15",
        "id": "national_household_survey",
        "title": "National Household Survey 2011",
        "description": "Please add a description here",
        "tags": ["household","survey","tenure","mobility"],
        "path": articles_national_household_survey_path
      },
      {
        "author": "John Doe",
        "date": "2017-02-15",
        "id": "interesting_insights",
        "title": "Interesting Insights",
        "description": "Please add a description here",
        "tags": ["insights","interesting","bubble"],
        "path": articles_interesting_insights_path
      }
    ]
  end

  def provincial
    @bc_provincial_data = File.read("#{Rails.root}/public/data/bc_provincial_data.json")
  end

  def development_region
    @dev_region_transaction_data = File.read("#{Rails.root}/public/data/dev_region_transaction_data.json")
    @dev_region_geo_data = File.read("#{Rails.root}/public/data/dev_region_geo_data.geojson")
    @census_population_data = File.read("#{Rails.root}/public/data/census_population_data.json")
  end

  def municipal
    @municipal_transaction_data = File.read("#{Rails.root}/public/data/municipal_transaction_data.json")
    @regional_district_geo_data = File.read("#{Rails.root}/public/data/regional_district_geo_data.geojson")
    @municipal_population = File.read("#{Rails.root}/public/data/municipal_population.json")
  end

  def census_bc
    @census_population_data = File.read("#{Rails.root}/public/data/census_population_data.json")
    @census_population_geo_data = File.read("#{Rails.root}/public/data/census_population_geo_data.geojson")
  end

  def national_household_survey
    @national_household_survey_data = File.read("#{Rails.root}/public/data/national_household_survey_data.json")
    @household_mobility_status_data = File.read("#{Rails.root}/public/data/household_mobility_status_data.json")
  end

  def interesting_insights
    @dev_region_transaction_data = File.read("#{Rails.root}/public/data/dev_region_transaction_data.json")
    @municipal_transaction_data = File.read("#{Rails.root}/public/data/municipal_transaction_data.json")
    @census_population_data = File.read("#{Rails.root}/public/data/census_population_data.json")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  
  def image_exist(path)
    if File.file?("#{Rails.public_path}" + path)
      true
    else
      false
    end
  end


end

app/views/articles/_header.html.erb
<div class="header">
  <div class="container">
    <div class="title">Data Visualization Challenge</div>
    <div class="author">by Ho Seok (Brandon) Oh</div>
  </div>
</div>

app/views/articles/census_bc.html.erb
<input id="census_population_data" value="<%= @census_population_data %>" type="hidden" />
<input id="census_population_geo_data" value="<%= @census_population_geo_data %>" type="hidden" />

<%= render "header"%>

<div class="container articles">
  <div class="navi">
    <%= link_to "Articles Home", articles_index_path %> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> Census of B.C. 2016
  </div>

  <h1 class="color-grey">Census of B.C. 2016</h1>
  <h3 class="color-grey">between 2011 and 2016</h3>

  <ul class="tab-list nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#analysis" aria-controls="analysis" role="tab" data-toggle="tab">Analysis</a>
    </li>
    <li role="presentation">
      <a href="#editorial" aria-controls="editorial" role="tab" data-toggle="tab">Editorial</a>
    </li>
    <li role="presentation">
      <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a>
    </li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="analysis">
      <div class="row analysis">
        <%= render "articles/census_bc/analysis" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="editorial">
      <div class="row editorial">
        <%= render "articles/util/editorial" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="comments">
      <div class="row comments">
        <%= render "articles/util/comments" %>
      </div>
    </div>
  </div>


</div>

app/views/articles/census_bc/_analysis.html.erb
<!-- Left panel -->
<div class="col-md-9" id="census_bc_charts">

  <select id="census_bc_select">
    <option value="regional_district">Population Change in Regional Districts</option>
    <option value="canada_bc">Overview of Canada and B.C.</option>
    <option value="dev_region">Overview of Development Regions</option>
  </select>

  <select id="canada_bc_select" style="display:none">
    <option value="">Select</option>
    <option value="population">Population</option>
    <option value="total_private_dwellings">Total Private Dwellings</option>
    <option value="private_dwellings_residents_canada_bc">Private dwellings occupied by usual residents of Canada and B.C. in 2016</option>
    <option value="percentage_private_dwellings_residents_canada_bc">Percentage of Private Dwellings between usual residents and others of Canada and B.C. in 2016</option>
    <option value="population_change_dwellings_change">Population Change and Total private dwellings Change</option>
    <option value="population_comparison_bc_rest">Population Comparison of B.C. and Rest</option>
    <option value="land_area_population_denisty">Land area and Population Density</option>
  </select>

  <div class="article" id="regional_district">
    <div class="article-header">
      <h3 class="color-darkblue">Population Change in Regional Districts</h3>
      <p class="color-grey">Source: Statistics Canada</p>
    </div>

    <div class="article-body">
     <%= render "articles/census_bc/regional_districts_map" %>
    </div>
  </div>


  <div class="article" id="canada_bc" style="display:none">
    <div class="article-header">
      <h3 class="color-darkblue">Overview of Canada and B.C.</h3>
      <p class="color-grey">Source: Statistics Canada</p>
    </div>

    <div class="article-body">
     <%= render "articles/census_bc/overview_canada_bc" %>
    </div>
  </div>


  <div class="article" id="dev_region" style="display:none">
    <div class="article-header">
      <h3 class="color-darkblue">Overview of Development Regions</h3>
      <p class="color-grey">Source: Statistics Canada</p>
    </div>

    <div class="article-body">
      <%= render "articles/census_bc/dev_region_population" %>
    </div>
  </div>

</div>


<!-- Right panel -->
<div class="col-md-3">
  <%= render "articles/util/right_panel_detail" %>
</div>


<script>
$(document).ready(function() {
  var start = "#census_bc_charts ";

  $(start + "#census_bc_select").on("change", function() {
    var census_bc_select = $(this).val();
    
    if (census_bc_select == "canada_bc") {
      $(start + ".article").hide();
      $(start + "#canada_bc").show();

      $(start + "#canada_bc_select").show();

    } else if (census_bc_select == "dev_region") {
      $(start + ".article").hide();
      $(start + "#dev_region").show();

      $(start + "#canada_bc_select").hide();

    } else if (census_bc_select == "regional_district") {
      $(start + ".article").hide();
      $(start + "#regional_district").show();

      $(start + "#canada_bc_select").hide();

    } else {
      $(start + ".article").hide();
      $(start + "#canada_bc_select").hide();
    }

  });

  $(start + "#canada_bc_select").on("change", function() {
    var canada_bc_select = $(this).val();

    if (canada_bc_select == "population") {
      $(start + ".canvases").hide();
      $(start + "#population").show();

    } else if (canada_bc_select == "total_private_dwellings") {
      $(start + ".canvases").hide();
      $(start + "#total_private_dwellings").show();

    } else if (canada_bc_select == "private_dwellings_residents_canada_bc") {
      $(start + ".canvases").hide();
      $(start + "#private_dwellings_residents_canada_bc").show();

    } else if (canada_bc_select == "percentage_private_dwellings_residents_canada_bc") {
      $(start + ".canvases").hide();
      $(start + "#percentage_private_dwellings_residents_canada_bc").show();

    } else if (canada_bc_select == "population_change_dwellings_change") {
      $(start + ".canvases").hide();
      $(start + "#population_change_dwellings_change").show();

    } else if (canada_bc_select == "population_comparison_bc_rest") {
      $(start + ".canvases").hide();
      $(start + "#population_comparison_bc_rest").show();

    } else if (canada_bc_select == "land_area_population_denisty") {
      $(start + ".canvases").hide();
      $(start + "#land_area_population_denisty").show();

    } else {
      $(start + ".canvases").hide();
    }

  });


});
</script>

app/views/articles/census_bc/_dev_region_population.html.erb
<div class="canvases">
  <p class="description">
    <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> 
    Please add a DESCRIPTION here
  </p>
  <h4 class="color-grey make-center">Population</h4>
  <canvas id="dev_region_population_canvas"></canvas>
  
  <div class="row">
    <div class="col-md-3 col-xs-2"></div>
    <div class="col-md-6 col-xs-8">
      <h4 class="color-grey make-center">Comparison of Population</h4>
      <canvas id="dev_region_population_pie_canvas"></canvas>
    </div>
    <div class="col-md-3 col-xs-2"></div>  
  </div>
</div>


<script>
$(document).ready(function() {

  // data
  var census_population_data = JSON.parse( $("#census_population_data").val() );
  var dev_region_population_data = census_population_data['canada_provinces_territories'][1]['development regions'];

  var regions = [];
  var populations = [];
  var dev_region_population_pie_bg = [];
  for (var i = 0; i < dev_region_population_data.length; i++) {
    regions.push( dev_region_population_data[i]['name'] );
    populations.push( dev_region_population_data[i]['Population, 2016'] );
    dev_region_population_pie_bg.push(colours[i]['rgba']['opacity-0.9']);
  }


  // make a bar chart for population
  new Chart($("#dev_region_population_canvas"), {
    type: "horizontalBar",
    data: {
      labels: regions,
      datasets: [{
        label: "Population",
        data: populations,
        backgroundColor: colours[0]['rgba']['opacity-0.9']
      }]
    },
    options: horizontal_bar_option("Population (1M=1,000,000)", 1000000, "M")
  });

  // make a pie chart for population of each development region
  new Chart($("#dev_region_population_pie_canvas"), {
    type: "pie",
    data: {
      labels: regions,
      datasets: [{
        data: populations,
        backgroundColor: dev_region_population_pie_bg
      }]
    },
    options: pie_option()
  });


});
</script>

app/views/articles/census_bc/_regional_districts_map.html.erb
<p class="description">
  <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> 
  Please add a DESCRIPTION here
</p>

<div id="census_population_map" class="choropleth_map"></div>

<div class="click_region">
  <%= render "articles/census_bc/click_region" %>
</div>

<script>
$(document).ready(function() {
  var census_population_data = JSON.parse( $("#census_population_data").val() );

  var map = L.map('census_population_map',{scrollWheelZoom:false}).setView([54.6000,-123.0000], 5);

  L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
  }).addTo(map);
  

  var census_population_geo_data = $("#census_population_geo_data").val();
  var geojson;
  
  geojson = L.geoJson(JSON.parse(census_population_geo_data), {
    style: style,
    onEachFeature: onEachFeature
  }).addTo(map);


  var info = L.control();
  info.onAdd = function(map) {
    this._div = L.DomUtil.create('div', 'info');
    this.update();
    return this._div;
  };

  info.update = function(props) {

    var html = "<h4>Information</h4>";

    if (props) {
      var change = add_comma(props.change, 2);
      var pop = add_comma(props.population, 0);
      var area = add_comma(props.land_area, 2);
      var density = add_comma(props.density, 2);
      var national_rank = add_comma(props.national_population_rank, 0);
      var provincial_rank = add_comma(props.provincial_population_rank, 0);
      var num_municipality = add_comma(props.num_municipality, 0);

      html += "<div class='map-title color-darkblue'><b>" + props.name + "</b></div>" +
              "<ul class='map-info'>" +
                "<li>Change (%): " + change + "</li>" +
                "<li>Population: " + pop + "</li>" +
                "<li>Land Area (sq. km): " + area + "</li>" +
                "<li>Population Density per sq. km: " + density + "</li>" +
                "<li>National Population Rank: " + national_rank + "</li>" +
                "<li>Provincial Population Rank: " + provincial_rank + "</li>" +
              "</ul>";

    } else {
      html += "Click or hover over each area";
    }

    this._div.innerHTML = html;
  };
  info.addTo(map);


  var legend = L.control({position: 'bottomright'});

  legend.onAdd = function(map) {

      var div = L.DomUtil.create('div', 'info legend'),
          grades = [-15.5, -10.5, -5.5, -0.5, 0.5, 5.5, 10.5, 15.5],
          labels = [];

      for (var i = 0; i < grades.length; i++) {
          div.innerHTML +=
              '<i style="background:' + getColor(grades[i] + 1) + '"></i> ' +
              grades[i] + (grades[i + 1] ? '&ndash;' + grades[i + 1] + '<br>' : '+');
      }

      return div;
  };

  legend.addTo(map);


  function getColor(d) {
    return d > 15.5 ? '#800026' :
      d > 10.5  ? '#BD0026' :
      d > 5.5  ? '#E31A1C' :
      d > 0.5  ? '#FEB24C' :
      d > -0.5   ? '#FFEDA0' :
      d > -5.5   ? '#7f95ef' :
      d > -10.5   ? '#7865f2' :
      '#0e025b';
  }

  function style(feature) {
      return {
          fillColor: getColor(feature.properties.change),
          weight: 2,
          opacity: 1,
          color: 'white',
          dashArray: '3',
          fillOpacity: 0.7
      };
  }

  function highlightFeature(e) {
      var layer = e.target;

      layer.setStyle({
          weight: 3,
          color: 'rgba(54, 162, 235, 1)',
          dashArray: '',
          fillOpacity: 0.7
      });

      if (!L.Browser.ie && !L.Browser.opera && !L.Browser.edge) {
          layer.bringToFront();
      }
      info.update(layer.feature.properties);
  }

  function resetHighlight(e) {
      geojson.resetStyle(e.target);
      info.update();
  }

  function zoomToFeature(e) {
      map.fitBounds(e.target.getBounds());
  }

  function onEachFeature(feature, layer) {
    layer.on({
      mouseover: highlightFeature,
      mouseout: resetHighlight,
      click: clickFeature
    });
  }

  function clickFeature(e) {
    var regions = census_population_data['canada_provinces_territories'][1]['development regions'];

    var id = "Null";
    for (var i = 0; i < regions.length; i++) {
      var regional_district = regions[i]['regional district'];
      for (var j = 0; j < regional_district.length; j++) {
        if (regional_district[j]['name'] == e.target.feature.properties.name) {
          id = regional_district[j]['id'];
        }
      }
    }

    if (id == "Null") console.log("There no relevant region");
    else $("#" + id + "Modal").modal("show");
  }


});
</script>

app/views/articles/development_region.html.erb
<input id="dev_region_geo_data" value="<%= @dev_region_geo_data %>" type="hidden" />
<input id="dev_region_transaction_data" value="<%= @dev_region_transaction_data %>" type="hidden" />
<input id="census_population_data" value="<%= @census_population_data %>" type="hidden" />

<%= render "header"%>

<div class="container articles">

  <div class="navi">
    <%= link_to "Articles Home", articles_index_path %> 
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> 
    Development Region
  </div>
  
  <h1 class="color-grey">Development Region Monthly</h1>
  <h3 class="color-grey">for Property Transfer Tax (June ~ Dec. 2016)</h3>

  <ul class="tab-list nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#analysis" aria-controls="analysis" role="tab" data-toggle="tab">Analysis</a>
    </li>
    <li role="presentation">
      <a href="#editorial" aria-controls="editorial" role="tab" data-toggle="tab">Editorial</a>
    </li>
    <li role="presentation">
      <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a>
    </li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="analysis">
      <div class="row analysis">
        <%= render "articles/development_region/analysis" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="editorial">
      <div class="row editorial">
        <%= render "articles/util/editorial_ptt" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="comments">
      <div class="row comments">
        <%= render "articles/util/comments" %>
      </div>
    </div>
  </div>

</div>

app/views/articles/development_region/_fmv_population.html.erb
<div class="canvases">
  <p class="description">
    <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> 
    Please add a DESCRIPTION here
  </p>
  <canvas id="fmv_population_canvas"></canvas>
  <p class="color-grey">Note: Diameter = Sum of Property Transfer Tax (PTT) paid / 10,000,000</p>
</div>


<script>
$(document).ready(function() {

  var dev_region_transaction_data = JSON.parse( $("#dev_region_transaction_data").val() );
  var months = dev_region_transaction_data['months'];
  var dev_region = dev_region_transaction_data['development_region'];

  var census_population_data = JSON.parse( $("#census_population_data").val() );

  var fmv_population_dataset = [];

  var dividend = 10000000;
  for (var i = 0; i < dev_region.length; i++) {
    var name = dev_region[i]['name'];
    var fmv = dev_region[i]['fair market value']['sum_FMV'];
    var ptt = dev_region[i]['property transfer tax']['sum_PTT_paid'];
    var population = census_population_data['canada_provinces_territories'][1]['development regions'][i]['Population, 2016'];

    fmv_population_dataset.push({
      label: name,
      data: [{x: population, y: fmv, r: ptt/dividend}],
      backgroundColor: colours[i]['rgba']['opacity-0.9'],
      hoverBackgroundColor: colours[i]['rgba']['opacity-1'],
    });
  }

  new Chart($("#fmv_population_canvas"), {
    type: "bubble",
    data: {
      datasets: fmv_population_dataset
    },
    options: bubble_option("Population (1M=1,000,000)", 1000000, "M", "Sum FMV, Dollars (1B=1,000,000,000)", 1000000000, "B")
  });


});
</script>

app/views/articles/interesting_insights.html.erb
<input id="dev_region_transaction_data" value="<%= @dev_region_transaction_data %>" type="hidden" />
<input id="municipal_transaction_data" value="<%= @municipal_transaction_data %>" type="hidden" />
<input id="census_population_data" value="<%= @census_population_data %>" type="hidden" />


<%= render "header"%>

<div class="container articles">

  <div class="navi">
    <%= link_to "Articles Home", articles_index_path %> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> Interesting Insights
  </div>


  <h1 class="color-grey">Interesting Insights</h1>
  
  <ul class="tab-list nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#analysis" aria-controls="analysis" role="tab" data-toggle="tab">Analysis</a>
    </li>
    <li role="presentation">
      <a href="#editorial" aria-controls="editorial" role="tab" data-toggle="tab">Editorial</a>
    </li>
    <li role="presentation">
      <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a>
    </li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="analysis">
      <div class="row analysis">
        <%= render "articles/interesting_insights/analysis" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="editorial">
      <div class="row editorial">
        <%= render "articles/util/editorial" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="comments">
      <div class="row comments">
        <%= render "articles/util/comments" %>
      </div>
    </div>
  </div>


</div>

app/views/articles/municipal.html.erb
<input id="municipal_transaction_data" value="<%= @municipal_transaction_data %>" type="hidden" />
<input id="municipal_population" value="<%= @municipal_population %>" type="hidden" />
<input id="regional_district_geo_data" value="<%= @regional_district_geo_data %>" type="hidden" />

<%= render "header"%>

<div class="container articles">

  <div class="navi">
    <%= link_to "Articles Home", articles_index_path %> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> Municipal
  </div>

  <h1 class="color-grey">Municipal Monthly</h1>
  <h3 class="color-grey">for Property Transfer Tax (June ~ Dec. 2016)</h3>
  
  <ul class="tab-list nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#analysis" aria-controls="analysis" role="tab" data-toggle="tab">Analysis</a>
    </li>
    <li role="presentation">
      <a href="#editorial" aria-controls="editorial" role="tab" data-toggle="tab">Editorial</a>
    </li>
    <li role="presentation">
      <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a>
    </li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="analysis">
      <div class="row analysis">
        <%= render "articles/municipal/analysis" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="editorial">
      <div class="row editorial">
        <%= render "articles/util/editorial" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="comments">
      <div class="row comments">
        <%= render "articles/util/comments" %>
      </div>
    </div>
  </div>

</div>

app/views/articles/national_household_survey.html.erb
<input id="household_mobility_status_data" value="<%= @household_mobility_status_data %>" type="hidden" />
<input id="national_household_survey_data" value="<%= @national_household_survey_data %>" type="hidden" />

<%= render "header"%>

<div class="container articles">
  <div class="navi">
    <%= link_to "Articles Home", articles_index_path %> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> Census Canada 2011
  </div>

  <h1 class="color-grey">National Household Survey 2011</h1>

  <ul class="tab-list nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#analysis" aria-controls="analysis" role="tab" data-toggle="tab">Analysis</a>
    </li>
    <li role="presentation">
      <a href="#editorial" aria-controls="editorial" role="tab" data-toggle="tab">Editorial</a>
    </li>
    <li role="presentation">
      <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a>
    </li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="analysis">
      <div class="row analysis">
        <%= render "articles/national_household_survey/analysis" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="editorial">
      <div class="row editorial">
        <%= render "articles/util/editorial_household" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="comments">
      <div class="row comments">
        <%= render "articles/util/comments" %>
      </div>
    </div>
  </div>


</div>

app/views/articles/provincial.html.erb
<input id="bc_provincial_data" value="<%= @bc_provincial_data %>" type="hidden" />

<%= render "header"%>

<div class="container articles">
  <div class="navi">
    <%= link_to "Articles Home", articles_index_path %> 
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> 
    Provincial
  </div>

  <h1 class="color-grey">Provincial Monthly</h1>
  <h3 class="color-grey">for Property Transfer Tax (June ~ Dec. 2016)</h3>

  <ul class="tab-list nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
      <a href="#analysis" aria-controls="analysis" role="tab" data-toggle="tab">Analysis</a>
    </li>
    <li role="presentation">
      <a href="#editorial" aria-controls="editorial" role="tab" data-toggle="tab">Editorial</a>
    </li>
    <li role="presentation">
      <a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a>
    </li>
  </ul>

  <div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="analysis">
      <div class="row analysis">
        <%= render "articles/provincial/analysis" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="editorial">
      <div class="row editorial">
        <%= render "articles/util/editorial_ptt" %>
      </div>
    </div>
    <div role="tabpanel" class="tab-pane fade" id="comments">
      <div class="row comments">
        <%= render "articles/util/comments" %>
      </div>
    </div>
  </div>

</div>

app/views/articles/util/_comments.html.erb
<div class="col-md-12">
	<div class="comment">
		<%= fa_icon "info-circle" %> Please post any comments here
	</div>
</div>

app/views/articles/util/_data_dictionary_national_household_survey.html.erb
<ul>
  <li><b>Tenure</b>: refers to whether the household owns or rents their private dwelling. The private dwelling may be situated on rented or leased land or be part of a condominium. A household is considered to own their dwelling if some member of the household owns the dwelling even if it is not fully paid for, for example if there is a mortgage or some other claim on it. A household is considered to rent their dwelling if no member of the household owns the dwelling. A household is considered to rent that dwelling even if the dwelling is provided without cash rent or at a reduced rent, or if the dwelling is part of a cooperative.</li>
  <li><b>Private household</b>: refers to a person or group of persons who occupy the same dwelling and do not have a usual place of residence elsewhere in Canada or abroad. The household universe is divided into two sub-universes on the basis of whether the household is occupying a collective dwelling or a private dwelling. The latter is a private household.</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataVisualization</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>